"""empty message

Revision ID: 00520ea1f8b6
Revises: 
Create Date: 2019-04-22 20:22:09.557903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00520ea1f8b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rents', sa.Column('rent_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rents', 'rent_price')
    # ### end Alembic commands ###
